### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by amit-ib** [amit-ib/Todo-v2#1]
**Phase - 1  - App with Static Data**
- [x] TD0001-Folder structuring
- [x] TD0002-Add non working form and static Todo list
- [x] TD0003-Functionality to add new task
- [x] TD0004-Functionality to mark task as done
- [x] TD0005-Functionality to edit task
- [x] TD0006-Functionality to delete task
- [x] TD0007-Show confirmation dialog on deleting any task

**Phase - 1 : Good to have**
- [x] TD0008-Implement filter list functionality  
- [x] TD0009-Sort items to display latest on top 
- [x] TD00010-Google Login Authentication  
- [x] Delete on swiping
- [x] Archive on swiping
- [x] Animate on deleting any task
- [x] Set task priority with color/flag/icon
- [ ] Grid/List View
- [x] Show count for All/pending/done
- [ ] Sort by date/task/status

**Phase - 2**
- [x] TD00011-Add date with task
- [x] TD00012-Change date for already added task

**Phase - 3**
- [x] TD00014-Use Redux/Stores
- [x] TD00015-Introduce database and store todos in it

**Scalability Scope**
- [ ] Add option for reminder before X days, either with email or some other way
- [ ] Add super admin, who can manage and assign tasks to other users along with other features like
   - [ ] Manage projects
   - [ ] Manage task categories
   - [ ] Manage tasks status
   - [ ] Assign tasks to other users
   - [ ] View tasks of any user

**Email Functionality**
- [ ] Option to setup email configuration
   - [ ] Email Notification - checkbox
   - [ ] Reminder - dropdown with the option to select the reminder email before X number of days example "1 Day", "5 Days"
   - [ ] Frequency - radio (daily/once)
   - [ ] Cancel & Save - button

Inputs from Sachin
   - [x] A user can assign task to any other user along with setting its priority level
   - [ ] while adding a task use we can add special char to assign its category, status or else
   - [ ] Shoot email on performing any action

**Updations**
- [ ] TDM0001-Updation as per code review
- [ ] TDM0002-UI Related changes

**URL**
https://todo-3dec9.web.app/

**Comment by amit-ib** [comment]
- **PROCCESS**
 - Tickets
 - Smart Commits
 - Planning
 - CD/CI Process
 - Designing
 - **JavaScript**
 - Logic Creation
 - GitHub
 - Separation of Concern

**Comment by akash-dhande-ib** [comment]
Hi @amit-ib

In which phase we are currently?

Thanks

**Comment by amit-ib** [comment]
> 

Hi @akash-dhande-ib 

We are in 1st phase.

Thanks

**Comment by akash-dhande-ib** [comment]
> > 
> 
> Hi @akash-dhande-ib
> 
> We are in 1st phase.
> 
> Thanks

Ok, let's finish this first then we will improvise it.

**Comment by amit-ib** [comment]
> > > 
> > 
> > 
> > Hi @akash-dhande-ib
> > We are in 1st phase.
> > Thanks
> 
> Ok, let's finish this first then we will improvise it.

I raised 1 PR today, kindly review and share your inputs, Thanks

**Comment by akash-dhande-ib** [comment]
> > > > 
> > > 
> > > 
> > > Hi @akash-dhande-ib
> > > We are in 1st phase.
> > > Thanks
> > 
> > 
> > Ok, let's finish this first then we will improvise it.
> 
> I raised 1 PR today, kindly review and share your inputs, Thanks

Shared
